# How do I change the data type of a pandas Series?

In [1]:
import pandas as pd

In [2]:
drinks = pd.read_csv('http://bit.ly/drinksbycountry')
drinks.head(15)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe
10,Azerbaijan,21,46,5,1.3,Europe
11,Bahamas,122,176,51,6.3,North America
12,Bahrain,42,63,7,2.0,Asia
13,Bangladesh,0,0,0,0.0,Asia
14,Barbados,143,173,36,6.3,North America

In [3]:
# to see data types for columns
drinks.dtypes

country                          object
beer_servings                     int64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object

In [5]:
# now to change data type, we use astype method
drinks['beer_servings'] = drinks.beer_servings.astype(float)
drinks.beer_servings

0        0.0
1       89.0
2       25.0
3      245.0
4      217.0
       ...
188    333.0
189    111.0
190      6.0
191     32.0
192     64.0
Name: beer_servings, Length: 193, dtype: float64

In [6]:
drinks.head(15)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0.0,0,0,0.0,Asia
1,Albania,89.0,132,54,4.9,Europe
2,Algeria,25.0,0,14,0.7,Africa
3,Andorra,245.0,138,312,12.4,Europe
4,Angola,217.0,57,45,5.9,Africa
5,Antigua & Barbuda,102.0,128,45,4.9,North America
6,Argentina,193.0,25,221,8.3,South America
7,Armenia,21.0,179,11,3.8,Europe
8,Australia,261.0,72,212,10.4,Oceania
9,Austria,279.0,75,191,9.7,Europe
10,Azerbaijan,21.0,46,5,1.3,Europe
11,Bahamas,122.0,176,51,6.3,North America
12,Bahrain,42.0,63,7,2.0,Asia
13,Bangladesh,0.0,0,0,0.0,Asia
14,Barbados,143.0,173,36,6.3,North America

In [7]:
# we can also change data type before reading csv file
drinks = pd.read_csv('http://bit.ly/drinksbycountry', dtype={'beer_servings':float})
drinks.dtypes

country                          object
beer_servings                   float64
spirit_servings                   int64
wine_servings                     int64
total_litres_of_pure_alcohol    float64
continent                        object
dtype: object