# How do I handle missing values in pandas?

In [1]:
import pandas as pd

In [2]:
ufo = pd.read_csv('https://bit.ly/uforeports')
ufo.head(15)

,City,Colors Reported,Shape Reported,State,Time
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00
3,Abilene,NaN,DISK,KS,6/1/1931 13:00
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00
5,Valley City,NaN,DISK,ND,9/15/1934 15:30
6,Crater Lake,NaN,CIRCLE,CA,6/15/1935 0:00
7,Alma,NaN,DISK,MI,7/15/1936 0:00
8,Eklutna,NaN,CIGAR,AK,10/15/1936 17:00
9,Hubbard,NaN,CYLINDER,OR,6/15/1937 0:00
10,Fontana,NaN,LIGHT,CA,8/15/1937 21:00
11,Waterloo,NaN,FIREBALL,AL,6/1/1939 20:00
12,Belton,RED,SPHERE,SC,6/30/1939 20:00
13,Keokuk,NaN,OVAL,IA,7/7/1939 2:00
14,Ludington,NaN,DISK,MI,6/1/1941 13:00

In [3]:
# first method isnull to see null values in dataframe
ufo.isnull().tail(20)

        City  Colors Reported  Shape Reported  State   Time
18221  False             True           False  False  False
18222  False             True           False  False  False
18223  False             True            True  False  False
18224  False             True           False  False  False
18225  False             True           False  False  False
18226  False             True           False  False  False
18227  False             True           False  False  False
18228  False             True           False  False  False
18229  False             True           False  False  False
18230  False             True           False  False  False
18231  False             True           False  False  False
18232  False             True            True  False  False
18233  False            False           False  False  False
18234  False             True           False  False  False
18235  False             True            True  False  False
18236  False             True           False  False  False
18237  False             True           False  False  False
18238  False             True            True  False  False
18239  False            False           False  False  False
18240  False             True           False  False  False

In [4]:
# as it, we have also notnull method
ufo.notnull().tail(15)

       City  Colors Reported  Shape Reported  State  Time
18226  True            False            True   True  True
18227  True            False            True   True  True
18228  True            False            True   True  True
18229  True            False            True   True  True
18230  True            False            True   True  True
18231  True            False            True   True  True
18232  True            False           False   True  True
18233  True             True            True   True  True
18234  True            False            True   True  True
18235  True            False           False   True  True
18236  True            False            True   True  True
18237  True            False            True   True  True
18238  True            False           False   True  True
18239  True             True            True   True  True
18240  True            False            True   True  True

In [5]:
# now, how we can benifit from them, first to know number of missing values in each column
ufo.isnull().sum()

City                  26
Colors Reported    15359
Shape Reported      2644
State                  0
Time                   0
dtype: int64

In [7]:
# now if we want to see the rows with null values from specific column
ufo[ufo.City.isnull()] # so this will return the 25 rows

      City Colors Reported Shape Reported State              Time
21     NaN             NaN            NaN    LA    8/15/1943 0:00
22     NaN             NaN          LIGHT    LA    8/15/1943 0:00
204    NaN             NaN           DISK    CA   7/15/1952 12:30
241    NaN            BLUE           DISK    MT    7/4/1953 14:00
613    NaN             NaN           DISK    NV    7/1/1960 12:00
1877   NaN          YELLOW         CIRCLE    AZ    8/15/1969 1:00
2013   NaN             NaN            NaN    NH     8/1/1970 9:30
2546   NaN             NaN       FIREBALL    OH  10/25/1973 23:30
3123   NaN             RED       TRIANGLE    WV  11/25/1975 23:00
4736   NaN             NaN         SPHERE    CA   6/23/1982 23:00
5269   NaN             NaN            NaN    AZ   6/30/1985 21:30
6113   NaN             NaN          OTHER    CO   6/30/1989 22:30
6735   NaN             NaN      FORMATION    TX     4/1/1992 2:00
7208   NaN             NaN         CIRCLE    MI   10/4/1993 17:30
8828   NaN             NaN       TRIANGLE    WA  10/30/1995 21:30
8967   NaN             NaN        VARIOUS    CA   12/8/1995 18:00
9273   NaN             NaN       TRIANGLE    OH     5/1/1996 3:00
9388   NaN             NaN           OVAL    CA   6/12/1996 12:00
9587   NaN             NaN            EGG    FL   8/24/1996 15:00
10399  NaN             NaN       TRIANGLE    IL   6/15/1997 23:00
11625  NaN             NaN         CIRCLE    TX     6/7/1998 7:00
12441  NaN             RED       FIREBALL    WA  10/26/1998 17:58
15767  NaN             NaN      RECTANGLE    NV   1/21/2000 11:30
15812  NaN             NaN          LIGHT    NV     2/2/2000 3:00
16054  NaN           GREEN            NaN    FL    3/11/2000 3:30
16608  NaN             NaN         SPHERE    NY   6/15/2000 15:00

ok, now we see the missing values, but what we must do with them <br>
the common action, is to drop these rows

In [9]:
# check dataframe shape before and after dropping
ufo.shape

(18241, 5)

In [11]:
ufo.dropna(how='any').shape

(2486, 5)

In [14]:
# we can use subset parameter
ufo.dropna(subset=['City', 'Shape Reported'], how='any').shape

(15575, 5)

In [15]:
ufo.dropna(subset=['City', 'Shape Reported'], how='all').shape

(18237, 5)

In [17]:
# another action with missing value, is to fill them
ufo['Shape Reported'].value_counts(dropna=False)

Shape Reported
LIGHT        2803
NaN          2644
DISK         2122
TRIANGLE     1889
OTHER        1402
CIRCLE       1365
SPHERE       1054
FIREBALL     1039
OVAL          845
CIGAR         617
FORMATION     434
VARIOUS       333
RECTANGLE     303
CYLINDER      294
CHEVRON       248
DIAMOND       234
EGG           197
FLASH         188
TEARDROP      119
CONE           60
CROSS          36
DELTA           7
ROUND           2
CRESCENT        2
DOME            1
PYRAMID         1
FLARE           1
HEXAGON         1
Name: count, dtype: int64

In [19]:
ufo['Shape Reported'] = ufo['Shape Reported'].fillna(value='VARIOUS')

In [20]:
ufo['Shape Reported'].value_counts(dropna=False)

Shape Reported
VARIOUS      2977
LIGHT        2803
DISK         2122
TRIANGLE     1889
OTHER        1402
CIRCLE       1365
SPHERE       1054
FIREBALL     1039
OVAL          845
CIGAR         617
FORMATION     434
RECTANGLE     303
CYLINDER      294
CHEVRON       248
DIAMOND       234
EGG           197
FLASH         188
TEARDROP      119
CONE           60
CROSS          36
DELTA           7
ROUND           2
CRESCENT        2
DOME            1
PYRAMID         1
FLARE           1
HEXAGON         1
Name: count, dtype: int64