In [4]:
people = {
    "first": ["Maryam", 'Tia', 'Tima'], 
    "last": ["Skaik", 'lulu', 'lulu'], 
    "email": ["MaryamSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com']
}

In [2]:
import pandas as pd

In [12]:
df = pd.DataFrame(people)
df

    first   last                  email
0  Maryam  Skaik  MaryamSkaik@gmail.com
1     Tia   lulu      Tialulu@email.com
2    Tima   lulu     Timalulu@email.com

In [13]:
df['email']

0    MaryamSkaik@gmail.com
1        Tialulu@email.com
2       Timalulu@email.com
Name: email, dtype: object

In [14]:
df.set_index('email')

                        first   last
email
MaryamSkaik@gmail.com  Maryam  Skaik
Tialulu@email.com         Tia   lulu
Timalulu@email.com       Tima   lulu

In [11]:
df # didn't change

                        first   last
email
MaryamSkaik@gmail.com  Maryam  Skaik
Tialulu@email.com         Tia   lulu
Timalulu@email.com       Tima   lulu

In [15]:
df.set_index('email', inplace=True)
df

                        first   last
email
MaryamSkaik@gmail.com  Maryam  Skaik
Tialulu@email.com         Tia   lulu
Timalulu@email.com       Tima   lulu

In [16]:
df.index

Index(['MaryamSkaik@gmail.com', 'Tialulu@email.com', 'Timalulu@email.com'], dtype='object', name='email')

In [17]:
# this give benifit since email is unique so help identify rows
df.loc['MaryamSkaik@gmail.com', 'last']

'Skaik'

In [19]:
df.loc[0] # gives error, since index is not interger, so we have to use iloc

KeyError: 0

In [20]:
df.iloc[0]

first    Maryam
last      Skaik
Name: MaryamSkaik@gmail.com, dtype: object

In [21]:
# also we can reset index
df.reset_index(inplace=True)
df

                   email   first   last
0  MaryamSkaik@gmail.com  Maryam  Skaik
1      Tialulu@email.com     Tia   lulu
2     Timalulu@email.com    Tima   lulu