In [1]:
people = {
    "first": ["Maryam", 'Tia', 'Tima'], 
    "last": ["Skaik", 'lulu', 'lulu'], 
    "email": ["MarymSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [10]:
df['last'] == 'lulu'

0    False
1     True
2     True
Name: last, dtype: bool

In [11]:
filt = (df['last'] == 'lulu')

In [13]:
df[filt]

  first  last               email
1   Tia  lulu   Tialulu@email.com
2  Tima  lulu  Timalulu@email.com

In [14]:
# we will get same result with loc
df.loc[filt]

  first  last               email
1   Tia  lulu   Tialulu@email.com
2  Tima  lulu  Timalulu@email.com

In [15]:
df.loc[filt, 'email']

1     Tialulu@email.com
2    Timalulu@email.com
Name: email, dtype: object

In [20]:
filt = (df['last'] == 'lulu') & (df['first'] == 'Tia')

In [21]:
df.loc[filt, 'email']

1    Tialulu@email.com
Name: email, dtype: object

In [23]:
filt = (df['last'] == 'Skaik') | (df['first'] == 'Tia')
df.loc[filt, 'email']

0    MarymSkaik@gmail.com
1       Tialulu@email.com
Name: email, dtype: object

In [24]:
# the opposite 
df.loc[~filt, 'email']

2    Timalulu@email.com
Name: email, dtype: object