In [1]:
person = {
    "first": "Maryam", 
    "last": "Skaik", 
    "email": "MaryamSkaik@gmail.com"
}

In [2]:
people = {
    "first": ["Maryam"], 
    "last": ["Skaik"], 
    "email": ["MaryamSkaik@gmail.com"]
}

In [3]:
people = {
    "first": ["Maryam", 'Tia', 'Tima'], 
    "last": ["Skaik", 'lulu', 'lulu'], 
    "email": ["MaryamSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com']
}

In [4]:
people['email']

['MaryamSkaik@gmail.com', 'Tialulu@email.com', 'Timalulu@email.com']

In [5]:
# make a dataframe from dictionary
import pandas as pd

In [7]:
df = pd.DataFrame(people)
df

    first   last                  email
0  Maryam  Skaik  MaryamSkaik@gmail.com
1     Tia   lulu      Tialulu@email.com
2    Tima   lulu     Timalulu@email.com

In [8]:
df['last']

0    Skaik
1     lulu
2     lulu
Name: last, dtype: object

In [10]:
type(df['last'])

pandas.core.series.Series

In [11]:
# Series: is list of data, have an index

In [12]:
df.email

0    MaryamSkaik@gmail.com
1        Tialulu@email.com
2       Timalulu@email.com
Name: email, dtype: object

In [13]:
# if I want a list of values, so pass a list
df[['last','email']]

    last                  email
0  Skaik  MaryamSkaik@gmail.com
1   lulu      Tialulu@email.com
2   lulu     Timalulu@email.com

In [14]:
# to got columns
df.columns

Index(['first', 'last', 'email'], dtype='object')

In [16]:
# to got rows, we use loc, and iloc  functions
# iloc: give it the index
df.iloc[0] # return the first row

first                   Maryam
last                     Skaik
email    MaryamSkaik@gmail.com
Name: 0, dtype: object

In [17]:
# same if we want a list of values, we pass a list of indices
df.iloc[[0,1]]

    first   last                  email
0  Maryam  Skaik  MaryamSkaik@gmail.com
1     Tia   lulu      Tialulu@email.com

In [18]:
# also we can specify the columns we want also by it's index
df.iloc[[0,1], 2]

0    MaryamSkaik@gmail.com
1        Tialulu@email.com
Name: email, dtype: object

In [21]:
df.iloc[[0,1], [1,2]]

    last                  email
0  Skaik  MaryamSkaik@gmail.com
1   lulu      Tialulu@email.com

In [22]:
df.loc[[0,1]]

    first   last                  email
0  Maryam  Skaik  MaryamSkaik@gmail.com
1     Tia   lulu      Tialulu@email.com

In [25]:
# can use name of columns as index with loc
df.loc[[0,1], 'email']

0    MaryamSkaik@gmail.com
1        Tialulu@email.com
Name: email, dtype: object