In [12]:
people = {
    "first": ["Maryam", 'Tia', 'Tima', 'Sara', 'lulu'], 
    "last": ["Skaik", 'lulu', 'lulu', 'ahmed', 'lulu'], 
    "email": ["MarymSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com', 'SaraAhmed@email.com', 'lulu@email.com']
}

In [2]:
import pandas as pd

In [13]:
df = pd.DataFrame(people)

In [14]:
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com
3    Sara  ahmed   SaraAhmed@email.com
4    lulu   lulu        lulu@email.com

In [15]:
# to sort df we can use sort_values function, and secify the column to sort by
df.sort_values(by='last') # note for maryam -> S < a, since S is upper case, while a is lower case, and upper come before lower

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
3    Sara  ahmed   SaraAhmed@email.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com
4    lulu   lulu        lulu@email.com

In [16]:
# sort desc
df.sort_values(by='last', ascending=False) # now skaik is last one ):

    first   last                 email
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com
4    lulu   lulu        lulu@email.com
3    Sara  ahmed   SaraAhmed@email.com
0  Maryam  Skaik  MarymSkaik@gmail.com

In [17]:
# also we can sort by more than one field using list 
df.sort_values(by=['last', 'first'], ascending=False)

    first   last                 email
4    lulu   lulu        lulu@email.com
2    Tima   lulu    Timalulu@email.com
1     Tia   lulu     Tialulu@email.com
3    Sara  ahmed   SaraAhmed@email.com
0  Maryam  Skaik  MarymSkaik@gmail.com

In [18]:
# now if we want to sort by first col as asc, and other as desc, so make list also for ordering
df.sort_values(by=['last', 'first'], ascending=[True,False])

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
3    Sara  ahmed   SaraAhmed@email.com
4    lulu   lulu        lulu@email.com
2    Tima   lulu    Timalulu@email.com
1     Tia   lulu     Tialulu@email.com

In [19]:
# applay to our df
df.sort_values(by=['last', 'first'], ascending=[True,False], inplace=True)
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
3    Sara  ahmed   SaraAhmed@email.com
4    lulu   lulu        lulu@email.com
2    Tima   lulu    Timalulu@email.com
1     Tia   lulu     Tialulu@email.com

In [21]:
# now to resort index
df.sort_index()

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com
3    Sara  ahmed   SaraAhmed@email.com
4    lulu   lulu        lulu@email.com

In [22]:
df['last'].sort_values()

0    Skaik
3    ahmed
4     lulu
2     lulu
1     lulu
Name: last, dtype: object