In [1]:
people = {
    "first": ["Maryam", 'Tia', 'Tima'], 
    "last": ["Skaik", 'lulu', 'lulu'], 
    "email": ["MarymSkaik@gmail.com", 'Tialulu@email.com', 'Timalulu@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

    first   last                 email
0  Maryam  Skaik  MarymSkaik@gmail.com
1     Tia   lulu     Tialulu@email.com
2    Tima   lulu    Timalulu@email.com

In [5]:
df['first'] + ' ' + df['last']

0    Maryam Skaik
1        Tia lulu
2       Tima lulu
dtype: object

In [6]:
# to add a new column, we just make assignment
df['full_name'] = df['first'] + ' ' + df['last']
df

    first   last                 email     full_name
0  Maryam  Skaik  MarymSkaik@gmail.com  Maryam Skaik
1     Tia   lulu     Tialulu@email.com      Tia lulu
2    Tima   lulu    Timalulu@email.com     Tima lulu

In [7]:
# to reomve or delete a column, we use drop method
df.drop(columns=['first', 'last'])

                  email     full_name
0  MarymSkaik@gmail.com  Maryam Skaik
1     Tialulu@email.com      Tia lulu
2    Timalulu@email.com     Tima lulu

In [8]:
# same if we see df, it will be as it, to change it add inplace=True

In [9]:
df.drop(columns=['first', 'last'], inplace=True)
df

                  email     full_name
0  MarymSkaik@gmail.com  Maryam Skaik
1     Tialulu@email.com      Tia lulu
2    Timalulu@email.com     Tima lulu

In [10]:
# to return columns we deleted by using full_name
df['full_name'].str.split(' ', expand=True)

        0      1
0  Maryam  Skaik
1     Tia   lulu
2    Tima   lulu

In [11]:
# now we just give them names, and assign them
df[['first', 'last']] = df['full_name'].str.split(' ', expand=True)
df

                  email     full_name   first   last
0  MarymSkaik@gmail.com  Maryam Skaik  Maryam  Skaik
1     Tialulu@email.com      Tia lulu     Tia   lulu
2    Timalulu@email.com     Tima lulu    Tima   lulu

In [12]:
# to add new row
df = pd.concat([df, pd.DataFrame([{'first': 'Saly'}])])
df

                  email     full_name   first   last
0  MarymSkaik@gmail.com  Maryam Skaik  Maryam  Skaik
1     Tialulu@email.com      Tia lulu     Tia   lulu
2    Timalulu@email.com     Tima lulu    Tima   lulu
0                   NaN           NaN    Saly    NaN

In [13]:
people = {
    'first': ['Sara', 'Lamar'], 
    'last': ['Skaik', 'Skaik'], 
    'email': ['SaraSkaik@email.com', 'LamarSkaik@email.com']
}
df2 = pd.DataFrame(people)
df2

   first   last                 email
0   Sara  Skaik   SaraSkaik@email.com
1  Lamar  Skaik  LamarSkaik@email.com

In [14]:
# now we want to add df2 to df
df = pd.concat([df, df2], ignore_index=True)
df

                  email     full_name   first   last
0  MarymSkaik@gmail.com  Maryam Skaik  Maryam  Skaik
1     Tialulu@email.com      Tia lulu     Tia   lulu
2    Timalulu@email.com     Tima lulu    Tima   lulu
3                   NaN           NaN    Saly    NaN
4   SaraSkaik@email.com           NaN    Sara  Skaik
5  LamarSkaik@email.com           NaN   Lamar  Skaik

In [16]:
# to drop using index
df.drop(index=3, inplace=True)
df

                  email     full_name   first   last
0  MarymSkaik@gmail.com  Maryam Skaik  Maryam  Skaik
1     Tialulu@email.com      Tia lulu     Tia   lulu
2    Timalulu@email.com     Tima lulu    Tima   lulu
4   SaraSkaik@email.com           NaN    Sara  Skaik
5  LamarSkaik@email.com           NaN   Lamar  Skaik

In [17]:
filt = df['last'] == 'lulu'
df.drop(index=df[filt].index)

                  email     full_name   first   last
0  MarymSkaik@gmail.com  Maryam Skaik  Maryam  Skaik
4   SaraSkaik@email.com           NaN    Sara  Skaik
5  LamarSkaik@email.com           NaN   Lamar  Skaik